--- 
version: '3.3'
services:
  builder:
    build: 
      dockerfile: Dockerfile.build
      context: ./
    volumes:
      - data:/opt

  prod:
    image: tomcat:9.0.8-jre8-alpine
    volumes:
      - data:/usr/local/tomcat/webapps
    depends_on:
      - builder
    ports:
      - "8080:8080"

volumes:
  data:
