FROM ubuntu:20.04
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install unzip git default-jdk maven -y
RUN mkdir boxfuse
WORKDIR /boxfuse
RUN pwd && git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git . && mvn package && mv /target/*.war /opt/hello.war