FROM ubuntu:18.04
ENV TZ=Europe/Moscow
RUN apt-get update && apt-get install unzip git default-jdk maven -y
RUN mkdir boxfuse
WORKDIR /boxfuse
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git && mvn package && mv /boxfuse/target/*.war /opt/hello.war