---
version: '3.3'
services:
  stage:
    build: tomcat/
    command: > 
      sh -c "apt-get update &&
             apt-get install -y git && 
             apt-get install -y maven &&
             git clone "https://github.com/boxfuse/boxfuse-sample-java-war-hello.git"

  prod:
    image: alpine:3.14
    depends_on:
      - stage
    ports:
      - "8080:80"
